name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - uses: actions/checkout@v3

      # 2. Node.js 설정
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      # 3. pnpm 설치 (버전 8, install step skipped)
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8'
          run_install: false

      # 4. pnpm store 경로 설정을 프로젝트 디렉토리로 고정
      - name: Configure pnpm store path
        run: pnpm config set store-dir .pnpm-store

      # 5. pnpm 스토어 캐싱
      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: .pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # 6. 의존성 설치
      - name: Install dependencies
        run: pnpm install

      # 7. pnpm store 내용 확인 (디버깅용)
      - name: Verify pnpm store content after install
        run: ls -la .pnpm-store

      # 8. 패키지 빌드
      - name: Build the package
        run: pnpm run build

      # 9. npm에 배포
      - name: Publish to npm
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
